courses/urls.py
from django.urls import path, re_path
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.course_list, name='courses'),
    re_path(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)$', views.step_detail, name='step'),
    re_path(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),
]

learning_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('courses/', include('courses.urls', namespace='courses')),
    path('admin/', admin.site.urls),
    path('', views.home, name='home')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

courses/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title

class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    content = models.TextField(blank=True, default='')
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    class Meta:
        ordering = ['order',]

    def __str__(self):
        return self.title

courses/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from .models import Course, Step

# Create your views here.
def course_list(request):
    courses = Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses': courses})


def course_detail(request, pk):
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})


def step_detail(request, course_pk, step_pk):
    step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/step_detail.html', {'step': step})

learning_site/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

courses/templates/courses/course_detail.html
{% extends "layout.html" %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}
<article>
  <h2> {{ course.title }} </h2>
  {{ course.description }}

  <section>
    {% for step in course.step_set.all %}
      <h3><a href="{% url 'courses:step' course_pk=step.course.pk step_pk=step.pk %}">{{ step.title }}</a></h3>
      {{ step.description }}
    {% endfor %}
  </section>
</article>
{% endblock %}

courses/templates/courses/course_list.html
{% extends "layout.html" %}

{% block title %}Available Courses{% endblock %}

{% block content %}
<div class="card">
  {% for course in courses %}
    <header><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></header>
    <div class="card-copy">
      {{ course.description }}
    </div>
  {% endfor %}
</div>
{% endblock %}

courses/templates/courses/step_detail.html
{% extends "layout.html" %}

{% block title %}{{ step.title }} - {{ step.course.title }}{% endblock %}

{% block content %}
<article>
  <h2> <a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }} </a></h2>
  <h3> {{ step.title }} </h3>
  {{ step.content|linebreaks }}
</article>
{% endblock %}

templates/home.html
{% extends "layout.html" %}

{% block title %}Well hello there!{% endblock %}

{% block content %}
<h1>Welcome!</h1>
{% endblock %}

templates/layout.html
{% load static %}

<!doctype html>
<html>
  <head>
      <title>{% block title %} {% endblock %}</title>
      <link rel='stylesheet' href='{% static  "css/layout.css" %}'>
  </head>
  <body>
    <div class='site-container'>
      <nav>
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'courses:courses' %}">Courses</a>
      </nav>
      {% block content %} {% endblock %}
    </div>
  </body>
</html>